name: Integration Tests

on:
  workflow_dispatch:

jobs:

  common:
    name: common
    env:
      TEST_NAME: common
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2